import type { LucideIcon } from "lucide-react";
import {
  ArrowRightLeft,
  BadgePercent,
  Boxes,
  Calculator,
  ClipboardList,
  Coins,
  FileBarChart2,
  FolderOpen,
  FolderTree,
  GitBranchPlus,
  HandCoins,
  HardDrive,
  ImageIcon,
  LayoutDashboard,
  Network,
  Package,
  Percent,
  Receipt,
  RotateCcw,
  Scale,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  Star,
  Store,
  Shield,
  UserCog,
  Users,
  Wallet,
} from "lucide-react";
import type { Role } from "@/lib/api/types";

/** Commerce permissions accountants may access when `/me` omits a full grant list. */
export const ACCOUNTANT_COMMERCE_PERMS = [
  "PROCESS_RMA",
  "MANAGE_RMA",
  "VIEW_TRANSACT",
  "CONFIG_FEE",
  "PAYOUT_SELLER",
  "CALC_LAND_COST",
  "APPROVE_PAYOUT",
  "PROCESS_PAYOUT",
  "VIEW_MLM_TREE",
  "ADJUST_POINTS",
  "CONFIG_MLM",
] as const;

export type AdminNavItem = {
  href: string;
  /** i18n key under admin.nav.* */
  labelKey: string;
  icon: LucideIcon;
  permissions?: string[];
  /** When set, user must have at least one of these roles (in addition to permissions). */
  roles?: Role[];
  sa?: boolean;
  group?: "ops" | "commerce" | "system";
};

export const adminNavItems: AdminNavItem[] = [
  { href: "/admin", labelKey: "admin.nav.overview", icon: LayoutDashboard, group: "ops" },
  {
    href: "/admin/shops",
    labelKey: "admin.nav.shops",
    icon: Store,
    permissions: ["APPROVE_SELLER", "APPROVE_SHOP", "REJECT_SHOP", "SUSPEND_SHOP"],
    group: "ops",
  },
  {
    href: "/admin/products",
    labelKey: "admin.nav.products",
    icon: Package,
    permissions: ["APPROVE_PRODUCT", "REJECT_PRODUCT", "HIDE_PRODUCT"],
    roles: ["ADMIN", "SUPER_ADMIN"],
    group: "ops",
  },
  {
    href: "/admin/products-view",
    labelKey: "admin.nav.products",
    icon: Package,
    permissions: ["VIEW_PROD_BKG"],
    roles: ["WAREHOUSE"],
    group: "ops",
  },
  {
    href: "/admin/reviews",
    labelKey: "admin.nav.reviews",
    icon: Star,
    roles: ["ADMIN", "SUPER_ADMIN"],
    group: "ops",
  },
  {
    href: "/admin/inventory",
    labelKey: "admin.nav.inventory",
    icon: Boxes,
    permissions: ["VIEW_INVENTORY", "EDIT_INVENTORY"],
    roles: ["WAREHOUSE", "ADMIN", "SUPER_ADMIN"],
    group: "ops",
  },
  {
    href: "/admin/transfers",
    labelKey: "admin.nav.transfers",
    icon: ArrowRightLeft,
    permissions: ["SYNC_INVENTORY"],
    roles: ["WAREHOUSE", "ADMIN", "SUPER_ADMIN"],
    group: "ops",
  },
  {
    href: "/admin/categories",
    labelKey: "admin.nav.categories",
    icon: FolderTree,
    permissions: ["MANAGE_CONTENT"],
    group: "ops",
  },
  {
    href: "/admin/users",
    labelKey: "admin.nav.users",
    icon: Users,
    permissions: ["LOCK_USER", "UNLOCK_USER", "DELETE_USER", "VIEW_USERS", "DELETE_ACCOUNT"],
    group: "ops",
  },
  {
    href: "/admin/staff",
    labelKey: "admin.nav.staff",
    icon: UserCog,
    permissions: ["MANAGE_STAFF", "ASSIGN_ROLES"],
    group: "ops",
  },
  {
    href: "/admin/platform-staff",
    labelKey: "admin.nav.platformStaff",
    icon: Shield,
    permissions: ["MANAGE_STAFF", "ASSIGN_ROLES"],
    roles: ["ADMIN", "SUPER_ADMIN"],
    group: "ops",
  },
  {
    href: "/admin/customers",
    labelKey: "admin.nav.customers",
    icon: Users,
    permissions: ["VIEW_CUST_DATA"],
    roles: ["CS", "ACCOUNTANT", "ADMIN", "SUPER_ADMIN"],
    group: "ops",
  },
  {
    href: "/admin/audit-logs",
    labelKey: "admin.nav.audit",
    icon: ClipboardList,
    permissions: ["VIEW_AUDIT_LOG"],
    roles: ["ADMIN", "SUPER_ADMIN"],
    group: "ops",
  },
  {
    href: "/admin/orders",
    labelKey: "admin.nav.orders",
    icon: ShoppingBag,
    permissions: ["FORCE_CANCEL_ORDER", "CONFIRM_ORDER"],
    roles: ["CS", "WAREHOUSE", "ACCOUNTANT", "ADMIN", "SUPER_ADMIN"],
    group: "commerce",
  },
  {
    href: "/admin/rma",
    labelKey: "admin.nav.rma",
    icon: RotateCcw,
    permissions: ["PROCESS_RMA", "MANAGE_RMA"],
    roles: ["CS", "WAREHOUSE", "ACCOUNTANT", "ADMIN", "SUPER_ADMIN"],
    group: "commerce",
  },
  {
    href: "/admin/settlements",
    labelKey: "admin.nav.settlements",
    icon: Scale,
    permissions: ["VIEW_TRANSACT"],
    group: "commerce",
  },
  {
    href: "/admin/transactions",
    labelKey: "admin.nav.transactions",
    icon: Receipt,
    permissions: ["VIEW_TRANSACT"],
    group: "commerce",
  },
  {
    href: "/admin/payouts",
    labelKey: "admin.nav.payouts",
    icon: HandCoins,
    permissions: ["PAYOUT_SELLER"],
    group: "commerce",
  },
  {
    href: "/admin/wallet/payouts",
    labelKey: "admin.nav.walletPayouts",
    icon: Wallet,
    permissions: ["APPROVE_PAYOUT"],
    roles: ["ACCOUNTANT", "ADMIN", "SUPER_ADMIN"],
    group: "commerce",
  },
  {
    href: "/admin/wallet/adjust",
    labelKey: "admin.nav.walletAdjust",
    icon: Coins,
    permissions: ["ADJUST_POINTS"],
    roles: ["ACCOUNTANT", "ADMIN", "SUPER_ADMIN"],
    group: "commerce",
  },
  {
    href: "/admin/mlm",
    labelKey: "admin.nav.mlm",
    icon: Network,
    permissions: ["CONFIG_MLM", "VIEW_MLM_TREE"],
    roles: ["SUPER_ADMIN", "ACCOUNTANT", "ADMIN"],
    group: "commerce",
  },
  {
    href: "/admin/mlm/commissions/report",
    labelKey: "admin.nav.commissionReport",
    icon: FileBarChart2,
    roles: ["SUPER_ADMIN"],
    group: "commerce",
  },
  {
    href: "/admin/rank-tree",
    labelKey: "admin.nav.rankTree",
    icon: GitBranchPlus,
    permissions: ["CONFIG_MLM", "VIEW_MLM_TREE"],
    roles: ["SUPER_ADMIN", "ACCOUNTANT", "ADMIN"],
    group: "commerce",
  },
  {
    href: "/admin/landing-cost",
    labelKey: "admin.nav.landingCost",
    icon: Calculator,
    permissions: ["CALC_LAND_COST"],
    group: "commerce",
  },
  {
    href: "/admin/finance/configs",
    labelKey: "admin.nav.financeConfigs",
    icon: Percent,
    permissions: ["CONFIG_FEE"],
    roles: ["SUPER_ADMIN", "ACCOUNTANT"],
    group: "commerce",
  },
  {
    href: "/admin/promotions",
    labelKey: "admin.nav.promotions",
    icon: BadgePercent,
    permissions: ["APPROVE_PROMO", "MANAGE_PROMO"],
    group: "commerce",
  },
  {
    href: "/admin/banners",
    labelKey: "admin.nav.banners",
    icon: ImageIcon,
    permissions: ["MANAGE_CONTENT"],
    group: "commerce",
  },
  {
    href: "/admin/marketing",
    labelKey: "admin.nav.marketing",
    icon: FolderOpen,
    permissions: ["MANAGE_CONTENT"],
    group: "commerce",
  },
  {
    href: "/admin/backups",
    labelKey: "admin.nav.backups",
    icon: HardDrive,
    permissions: ["BACKUP_RESTORE"],
    sa: true,
    group: "system",
  },
  {
    href: "/admin/rbac",
    labelKey: "admin.nav.rbac",
    icon: ShieldCheck,
    permissions: ["CONFIG_SYS"],
    sa: true,
    group: "system",
  },
  {
    href: "/admin/dsar",
    labelKey: "admin.nav.dsar",
    icon: ShieldAlert,
    roles: ["ADMIN", "SUPER_ADMIN"],
    group: "system",
  },
  { href: "/admin/system", labelKey: "admin.nav.system", icon: Settings, sa: true, group: "system" },
];
